# Generated by Django 5.2.7 on 2025-12-05 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userprofile_address_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_aadhar_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
