# Generated by Django 5.2.7 on 2025-12-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadhaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaardatabase',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aadhaardatabase',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aadhaardatabase',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aadhaardatabase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='aadhaardatabase',
            name='aadhaar_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aadhaardatabase',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
