from django.db import models
from django.conf import settings
import random
import string


class IssueReport(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Fetched from profile
    reporter_first_name = models.CharField(max_length=50)
    reporter_middle_name = models.CharField(max_length=50, blank=True, null=True)
    reporter_last_name = models.CharField(max_length=50)

    # Form input fields
    issue_title = models.CharField(max_length=150, default="Issue Report")
    location = models.CharField(max_length=150)
    issue_description = models.TextField(max_length=500)
    image_url = models.CharField(max_length=500, blank=True, null=True)
    image_key = models.CharField(max_length=512, blank=True, null=True)

    # Autogenerated fields
    issue_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    updated_at = models.DateTimeField(auto_now=True)
    tracking_id = models.CharField(max_length=8, unique=True, editable=False, blank=False)

    def __str__(self):
        return f"Tracking ID: {self.tracking_id} - Issue at {self.location}"

    def get_reporter_full_name(self):
        if self.reporter_middle_name:
            return (
                f"{self.reporter_first_name} "
                f"{self.reporter_middle_name} "
                f"{self.reporter_last_name}"
            )
        return f"{self.reporter_first_name} {self.reporter_last_name}"

    def generate_tracking_id(self):
        """Generate an 8-character unique tracking ID"""
        # Generate random 8-character alphanumeric ID
        chars = string.ascii_uppercase + string.digits
        tracking_id = ''.join(random.choices(chars, k=8))
        
        # Ensure uniqueness with retry logic
        attempts = 0
        while IssueReport.objects.filter(tracking_id=tracking_id).exists() and attempts < 10:
            tracking_id = ''.join(random.choices(chars, k=8))
            attempts += 1
        
        # If still not unique (very unlikely), add timestamp
        if IssueReport.objects.filter(tracking_id=tracking_id).exists():
            import time
            timestamp = str(int(time.time()))[-4:]  # Last 4 digits of timestamp
            random_part = ''.join(random.choices(string.ascii_uppercase, k=4))
            tracking_id = f"{random_part}{timestamp}"
        
        return tracking_id

    def save(self, *args, **kwargs):
        # Generate tracking_id only on creation
        if not self.tracking_id:
            self.tracking_id = self.generate_tracking_id()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ['-issue_date']