from django.db import models
from django.conf import settings

class IssueReport(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Fetched from profile
    reporter_first_name = models.CharField(max_length=50)
    reporter_middle_name = models.CharField(max_length=50, blank=True, null=True)
    reporter_last_name = models.CharField(max_length=50)
    
    # Form input fields
    issue_title = models.CharField(max_length=150,default="Issue Report")
    location = models.CharField(max_length=150)
    issue_description = models.TextField(max_length=500)
    image_url = models.CharField(max_length=150, blank=True, null=True)
    # image_key = models.CharField(max_length=512, blank=True, null=True)
    
    # Autogenerated fields
    issue_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Issue at {self.location} - {self.get_status_display()}"

    def get_reporter_full_name(self):
        if self.reporter_middle_name:
            return f"{self.reporter_first_name} {self.reporter_middle_name} {self.reporter_last_name}"
        return f"{self.reporter_first_name} {self.reporter_last_name}"

    class Meta:
        ordering = ['-issue_date']