# Generated by Django 5.2.7 on 2025-10-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='issue_title',
            field=models.CharField(default='Untitled Issue', max_length=150),
            preserve_default=False,
        ),
    ]
