# Generated by Django 5.2.7 on 2025-10-25 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_issuereport_issue_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='issue_title',
        ),
    ]
