# Generated by Django 5.2.7 on 2025-10-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_issuereport_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='issue_title',
            field=models.CharField(default='Issue Report', max_length=150),
        ),
    ]
