# Generated by Django 5.2.7 on 2025-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_issuereport_issue_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='image_key',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
