# Generated by Django 5.2.7 on 2025-12-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_issuereport_image_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='image_key',
        ),
    ]
