# Generated by Django 5.2.7 on 2025-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_issuereport_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
