# Generated by Django 5.2.7 on 2025-12-05 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_issuereport_image_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuereport',
            name='reporter_first_name',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='reporter_last_name',
        ),
        migrations.RemoveField(
            model_name='issuereport',
            name='reporter_middle_name',
        ),
        migrations.AddField(
            model_name='issuereport',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
