# Generated by Django 5.2.7 on 2025-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_add_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='tracking_id',
            field=models.CharField(default='TEMP0001', editable=False, max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
