# Generated by Django 5.2.7 on 2025-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_make_tracking_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuereport',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
