# Generated by Django 5.2.7 on 2025-12-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_remove_issuereport_reporter_first_name_and_more'),
        ('report', '0008_alter_issuereport_image_url'),
    ]

    operations = [
    ]
