# Generated by Django 5.2.7 on 2025-12-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_merge_20251208_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='allocated_to',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='issuereport',
            name='department',
            field=models.TextField(default='Manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='tracking_id',
            field=models.CharField(default='TEMP0001', editable=False, max_length=8, unique=True),
        ),
    ]
