# Generated by Django 5.2.7 on 2026-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_issuereport_allocated_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuereport',
            name='completion_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='issue_title',
            field=models.CharField(default='Issue Report', max_length=80),
        ),
        migrations.AlterField(
            model_name='issuereport',
            name='location',
            field=models.CharField(max_length=500),
        ),
    ]
