# Generated by Django 5.2.7 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0012_issuereport_dislikes_issuereport_likes_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuereport",
            name="appeal_status",
            field=models.CharField(
                choices=[
                    ("not_appealed", "Not Appealed"),
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="not_appealed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issuereport",
            name="trust_score_delta",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="issuereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("rejected", "Rejected"),
                    ("resolved", "Resolved"),
                    ("closed", "Closed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
