# Generated by Django 5.2.7 on 2025-12-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
