# Generated by Django 5.2.7 on 2026-02-14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0012_issuereport_dislikes_issuereport_likes_comment"),
        ("users", "0004_emailotp_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="deactivated_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="trust_score",
            field=models.IntegerField(
                default=100,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(110),
                ],
            ),
        ),
        migrations.CreateModel(
            name="TrustScoreLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delta", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("FAKE_REPORT", "Fake Report"),
                            ("APPEAL_ACCEPTED", "Appeal Accepted"),
                            ("POST_BAN_RESTORE", "Post-Ban Restore"),
                            ("ISSUE_RESOLVED", "Issue Resolved"),
                            ("MANUAL_ADMIN_ADJUSTMENT", "Manual Admin Adjustment"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "appeal_status",
                    models.CharField(
                        choices=[
                            ("NOT_APPEALED", "Not Appealed"),
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_APPEALED",
                        max_length=15,
                    ),
                ),
                ("admin_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trust_logs",
                        to="report.issuereport",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_score_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
